debug: false # ?? ???? ?? ??? ???? ?
management.endpoints.web.exposure.include: "*" # Spring Boot Actuator Endpoints ? ????? ????? ???? ??

logging:
  level:
    com.tdf.community: debug # community ????? ??? ??
    org.springframework.web.servlet: debug # ?? debug ??? ? ?? Request, Response ??? ?
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA? ?? ??? ?? -> ????? ?? ???? ??

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  data.rest:
    base-path: /api
    detection-strategy: annotated

cloud:
  aws:
    s3:
      bucket: dogfoot-project
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false